#!/bin/bash
echo
echo
echo "start runing new container named quotes-ui"
echo
echo
podman run -d --rm --name quotes-ui -p 3000:8080 -e QUOTES_API_VERSION=v2 -v ~/DO188/labs/troubleshooting-lab/nginx.conf:/etc/nginx/ginx.conf:Z --network troubleshooting-lab registry.ocp4.example.com:8443/redhattraining/quotes-ui-versioning:1.0
