#Maintainer Le Xuan Vinh <vinhlx90@icloud.com>
#modified 20230501
FROM ubi9/ubi:latest

ARG APP_USER=

ENV APP_ROOT=/var/www/html/ \
    APP_USER=${APP_USER:-1001} \
    APP_PORT=8080 \
    APP_BIN_DIR=/usr/sbin/httpd 

RUN dnf install -y httpd && dnf clean all && \
    sed -i -e 's/^Listen 80/Listen 8080/g' /etc/httpd/conf/httpd.conf && \
    sed -i -e 's/^ServerName/#ServerName/g' /etc/httpd/conf/httpd.conf && \
    echo "ServerName 127.0.0.1" >> /etc/httpd/conf/httpd.conf && \
    chgrp -R 0 /var/log/httpd /var/run/httpd && \
    chmod -R g=u /var/log/httpd /var/run/httpd && \
    useradd --uid 1001 --system --gid 0 --shell /sbin/nolgin --comment "Default application user" default

LABEL io.openshift.expose-services="8080:http" \
      io.k8s.description="My custom httpd container application to practive" \
      io.openshift.tags="httpd, web server, apache, apache2"

COPY index.html $APP_ROOT

VOLUME $APP_ROOT

EXPOSE $APP_PORT

USER $APP_USER

ENTRYPOINT ["/usr/sbin/httpd"]

CMD ["-D", "FOREGROUND"]
